# Generated by Django 4.1.2 on 2022-10-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_problem_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='website',
        ),
    ]
